In [1]:
import pandas as pd

In [5]:
report_file = '../data/glosslm_report.csv'
df = pd.read_csv(report_file)
df.head()

,index,sentence_a,sentence_b,sentence_x,set_type,word_set,word_a,word_b,word_x,k,word_a_index,word_b_index,word_x_index,a_x_similarity,b_x_similarity,score
0,0,àpɾí jə̀və̀lɛ̀ðᴐ́ àpɾíɲá,àpɾí jàvlə̀dɛ̀ɛ̌ àpɾíɲá,àpɾí jvə̀lə̀dóǒ àpɾíɲá,tam_alternation,pull_tam,jə̀və̀lɛ̀ðᴐ́,jàvlə̀dɛ̀ɛ̌,jvə̀lə̀dóǒ,0,1:1,1:1,1:1,0.892684,0.900102,False
1,1,àpɾí jə̀və̀lɛ̀dᴐ́ àpɾíɲá,àpɾí jàvlèdè àpɾíɲá,àpɾí jvlèdᴐ́ᴐ̌ àpɾíɲá,tam_alternation,pull_tam,jə̀və̀lɛ̀dᴐ́,jàvlèdè,jvlèdᴐ́ᴐ̌,1,1:1,1:1,1:1,0.873031,0.849163,True
2,2,àpɾí jvə̀lɛ̀ðó àpɾíɲá,àpɾí jàvlə̀ðèě àpɾíɲá,àpɾí jə̀vlə̀ðóǒ àpɾíɲá,tam_alternation,pull_tam,jvə̀lɛ̀ðó,jàvlə̀ðèě,jə̀vlə̀ðóǒ,2,1:1,1:1,1:1,0.900687,0.914389,False
3,3,àpɾí jə̀vlèðó àpɾíɲá,àpɾí jàvə̂lə̀dè àpɾíɲá,àpɾí jə̀və̀lə̀dᴐ́ àpɾíɲá,tam_alternation,pull_tam,jə̀vlèðó,jàvə̂lə̀dè,jə̀və̀lə̀dᴐ́,3,1:1,1:1,1:1,0.923980,0.921483,True
4,4,àpɾí jvlèðᴐ́ᴐ̌ àpɾíɲá,àpɾí jàvlə̀ðèě àpɾíɲá,àpɾí jə̀vlə̀ðóǒ àpɾíɲá,tam_alternation,pull_tam,jvlèðᴐ́ᴐ̌,jàvlə̀ðèě,jə̀vlə̀ðóǒ,4,1:1,1:1,1:1,0.882828,0.914389,False

In [ ]:
df['score'] = df['score'].astype(float)
df['score'].describe()

count    1641.000000
mean        0.173675
std         0.378945
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: score, dtype: float64

In [8]:
df.groupby('word_set')['score'].describe()

              count      mean       std  min  25%  50%  75%  max
word_set
carry_tam     456.0  0.074561  0.262971  0.0  0.0  0.0  0.0  1.0
dog_nomacc      8.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
pull_tam      960.0  0.207292  0.405578  0.0  0.0  0.0  0.0  1.0
sheep_nomacc   20.0  0.050000  0.223607  0.0  0.0  0.0  0.0  1.0
stick_chop     12.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
sticks_stab     9.0  0.222222  0.440959  0.0  0.0  0.0  0.0  1.0
take_tam      176.0  0.278409  0.449495  0.0  0.0  0.0  1.0  1.0